apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dowlclientsystems.azurecr.io/dance-classes/backend:latest
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: backend-secret