"""Add notes field to lessons

Revision ID: 690b3f35cf5b
Revises: fc6f7d084a7b
Create Date: 2024-04-05 13:11:55.106883

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '690b3f35cf5b'
down_revision = 'fc6f7d084a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'notes')
    # ### end Alembic commands ###
