"""Add payments table

Revision ID: f131bde0bc77
Revises: 950fca951f18
Create Date: 2024-04-03 19:31:48.849663

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f131bde0bc77'
down_revision = '950fca951f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('payment_group_id_fkey', 'payment', type_='foreignkey')
    op.drop_column('payment', 'year')
    op.drop_column('payment', 'month')
    op.drop_column('payment', 'group_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('payment_group_id_fkey', 'payment', 'group', ['group_id'], ['id'])
    op.drop_column('payment', 'notes')
    # ### end Alembic commands ###
