"""Update students and many to many relationships

Revision ID: fc6f7d084a7b
Revises: f131bde0bc77
Create Date: 2024-04-04 14:58:51.398954

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fc6f7d084a7b'
down_revision = 'f131bde0bc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item')
    op.add_column('groupstudentlink', sa.Column('joined_at', sa.DateTime(), nullable=False))
    op.add_column('payment', sa.Column('day', sa.Date(), nullable=False))
    op.add_column('payment', sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('payment', sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('payment', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('student', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('responsible_adult_full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('responsible_adult_phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('student', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'created_at')
    op.drop_column('student', 'notes')
    op.drop_column('student', 'responsible_adult_phone_number')
    op.drop_column('student', 'responsible_adult_full_name')
    op.drop_column('student', 'city')
    op.alter_column('payment', 'notes',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('payment', 'reason')
    op.drop_column('payment', 'method')
    op.drop_column('payment', 'day')
    op.drop_column('groupstudentlink', 'joined_at')
    op.create_table('item',
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name='item_owner_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='item_pkey')
    )
    # ### end Alembic commands ###
